print("HELLO WORLD")
print(" I AM REVISING PYTHON HANDBOOK")
# print("THIS WORLD IS VERY BEAUTFUL PLACE LET US MAKE IT MORE PEACEFUL") # THIS WAS IGONRED BECAUSE IT IS A COMMENT
# THIS IS MY VERY FIRST PROGRAAME IN PYTHON
# PRINT IS A FUNCTION 
