print("HELLO WORLD")
# print("THIS WORLD IS VERY BEAUTFUL PLACE LET US MAKE IT MORE PEACEFUL") # THIS WAS IGNORED BECAUSE IT IS A COMMENT
# THIS IS MY VERY FIRST PROGRAAME IN PYTHON
# PRINT IS A FUNCTION 
