a = int(input("ENTER YOUR NUMBER 1: "))
b = int(input("ENTER YOUR NUMBER 2: "))
c = int(input("ENTER YOUR NUMBER 3: "))
d = int(input("ENTER YOUR NUMBER 4: "))
e = int(input("ENTER YOUR NUMBER 5: "))
print("number a is : ",a)
print("number b is : ",a)
print("number c is : ",b)
print("number d is : ",d)
print("number e is : ",e)
print (a+b+c+d+e)